CREATE DATABASE Scam;
USE Scam;
CREATE TABLE scam_info(id int,scam_title varchar(20),scam_category varchar(20),loss_ammount int,date_reported int);
ALTER TABLE scam_info ADD COLUMN victim_id int, ADD COLUMN(victim_contact int,location bigint,current_status int,resolved boolean);
SELECT * FROM scam_info;
ALTER TABLE scam_info RENAME COLUMN scam_title to s_title;
ALTER TABLE scam_info RENAME COLUMN scam_category to s_category;
ALTER TABLE scam_info RENAME COLUMN location to s_location;
ALTER TABLE scam_info RENAME COLUMN resolved to s_resolved;
ALTER TABLE scam_info RENAME COLUMN loss_ammount to financial_loss;
ALTER TABLE scam_info MODIFY COLUMN financial_loss bigint;
ALTER TABLE scam_info MODIFY COLUMN date_reported varchar(20);
ALTER TABLE scam_info MODIFY COLUMN victim_contact varchar(20);
ALTER TABLE scam_info MODIFY COLUMN s_location varchar(30);
ALTER TABLE scam_info MODIFY COLUMN current_status varchar(30);
DESC scam_info;
INSERT INTO scam_info values(1,'Email attack','Phishing',1000000,'15-01-2024',1,'victim1@gmail.com','Newyork','Investigating',false);
INSERT INTO scam_info values(2,'Fake online store','Fraud',200000,'25-02-2024',2,'victim2@gmail.com','Los Angeles','Closed',true);
INSERT INTO scam_info values(3,'Healthinsurance scam','Impersonisation',400000,'14-04-2024',3,'victim3@gmail.com','London','Pending',false);
INSERT INTO scam_info values(4,'Joboffer scam','Fraud',250000,'30-03-2024',4,'victim4@gmail.com','Japan','Closed',true);
INSERT INTO scam_info values(5,'Banking scam','Phishing',300000,'14-03-2024',5,'victim5@gmail.com','India','Resolved',true);
INSERT INTO scam_info values(6,'Workfromhome scam','Fraud',500000,'24-07-2024',6,'victim6@gmail.com','Bangalore','Pending',false);
INSERT INTO scam_info values(7,'Fake Antivirus scam','Fraud',80000,'25-02-2024',7,'victim7@gmail.com','Delhi','Investing',false);
INSERT INTO scam_info values(8,'Credit scam','Phishing',1000000,'22-11-2022',8,'victim8@gmail.com','Bangalore','Resolved',true);
INSERT INTO scam_info values(9,'Loan Scam','Fraud',540000,'22-06-2023',9,'victim9@gmail.com','Mysore','Investigating',false);
INSERT INTO scam_info values(10,'Charity scam','Fraud',85000,'25-07-2024',10,'victim10@gmail.com','Hassan','Pending',false);
INSERT INTO scam_info values(11,'Scholarship scam','Fraud',58000,'30-12-2023',11,'victim11@gmail.com','Bangalore','Resolved',true);
INSERT INTO scam_info values(12,'Phonepay scam','Phishing',30000,'23-03-2024',12,'victim12@gmail.com','Tumkur','Investing',false);
INSERT INTO scam_info values(13,'Socialmedia scam','Fraud',390000,'25-07-2024',13,'victim13@gmail.com','Mumbai','Pending',false);
INSERT INTO scam_info values(14,'Email attack','Phishing',470000,'30-12-2023',14,'victim14@gmail.com','Newyork','Resolved',true);
INSERT INTO scam_info values(15,'Joboffer scam','Fraud',150000,'25-08-2023',15,'victim15@gmail.com','London','Pending',false);
INSERT INTO scam_info values(16,'Paytm scam','Phishing',1240000,'27-10-2023',16,'victim16@gmail.com','Switzerland','Resolved',true);
INSERT INTO scam_info values(17,'Scholarship scam','Fraud',350000,'24-06-2024',17,'victim17@gmail.com','Hyderabad','Investigating',false);
INSERT INTO scam_info values(18,'Socialmedia scam','Fraud',300000,'15-06-2024',18,'victim18@gmail.com','Kolkata','Pending',false);
INSERT INTO scam_info values(19,'Loan scam','Fraud',290000,'02-03-2023',19,'victim19@gmail.com','Bangalore','Resolved',true);
INSERT INTO scam_info values(20,'Insurance scam','Fraud',730000,'25-04-2023',20,'victim20@gmail.com','Mysuru','Resolved',true);
SELECT * FROM scam_info;
UPDATE scam_info SET s_location='UK' where id=1;
UPDATE scam_info SET s_category='Phishing' where id=7;
UPDATE scam_info SET s_resolved=true where id=9;
UPDATE scam_info SET current_status='Resolved' where s_title='Loan scam';
UPDATE scam_info SET s_location='Mangalore' where id=12;
UPDATE scam_info SET s_category='Phishing' where s_title='Scholarship scam';
UPDATE scam_info SET financial_loss=200000 where id=11;
UPDATE scam_info SET s_category='Phishing' where s_title='Socialmedia scam';
UPDATE scam_info SET s_location='London' where id=16;
UPDATE scam_info SET victim_id=19 where id=18;
DELETE FROM scam_info where s_title='Email attack';
DELETE FROM scam_info where victim_id=19;
DELETE FROM scam_info where id=12;
SELECT * FROM scam_info where id=4 AND id=7;
SELECT * FROM scam_info where id=4 OR id=7;
SELECT * FROM scam_info where id in(2,4,7);
SELECT * FROM scam_info where id not in(2,4,7);
