CREATE DATABASE room;
USE room;
CREATE TABLE show_room(id int not null,showroom_name varchar(20) not null,location varchar(20) unique,total_cars int check (total_cars > 50),
manager_id int unique,rating int check(rating>=0 and rating<10),created_at timestamp,created_by varchar(20),modified_at timestamp,modified_by varchar(20));
SELECT * FROM show_room;
DESC show_room;
INSERT INTO show_room values(1,'AutoHub','Nelamangala',55,101,9,now(),'Admin',now(),'Admin');
INSERT INTO show_room values(2,'CarZone','Bangalore',100,102,9,now(),'Admin1',now(),'Manager1');
INSERT INTO show_room values(3,'Speedster','Mysore',105,103,7,now(),'Admin2',now(),'Manager2');
INSERT INTO show_room values(4,'DriveTime','Hassan',60,104,9,now(),'Admin3',now(),'Manager3');
INSERT INTO show_room values(5,'AutoMart','Hubli',90,105,8,now(),'Admin4',now(),'Manager4');
INSERT INTO show_room values(6,'CarNation','Udupi',65,106,6,now(),'Admin5',now(),'Manager5');
INSERT INTO show_room values(7,'MotorHouse','Tumkur',95,107,8,now(),'Admin6',now(),'Manager6');
INSERT INTO show_room values(8,'FastTrack','Belgaum',60,108,9,now(),'Admin7',now(),'Manager7');
INSERT INTO show_room values(9,'AutoDrive','Mangalore',80,109,7,now(),'Admin8',now(),'Manager8');
INSERT INTO show_room values(10,'CarWorld','Davangere',60,110,9,now(),'Admin9',now(),'Manager9');
INSERT INTO show_room values(11,'EliteMotors','Mandya',75,111,5,now(),'Admin10',now(),'Manager10');
INSERT INTO show_room values(12,'GalaxyAutos','Kolar',150,112,8,now(),'Admin11',now(),'Manager11');
INSERT INTO show_room values(13,'LuxCars','Bijapur',200,113,4,now(),'Admin12',now(),'Manager12');
INSERT INTO show_room values(14,'TurboCars','Raichur',180,114,7,now(),'Admin13',now(),'Manager13');
INSERT INTO show_room values(15,'MegaMotors','Gulbarga',190,115,6,now(),'Admin14',now(),'Manager14');
INSERT INTO show_room values(16,'SpeedyWheels','Chitradurga',150,116,9,now(),'Admin15',now(),'Manager15');
INSERT INTO show_room values(17,'TurboCars','Chikmaglur',75,117,5,now(),'Admin16',now(),'Manager16');
INSERT INTO show_room values(18,'AutoEmpire','Bagalkot',190,118,8,now(),'Admin17',now(),'Manager17');
INSERT INTO show_room values(19,'PrestigeCars','Shimogga',90,119,3,now(),'Admin18',now(),'Manager18');
INSERT INTO show_room values(20,'PrimeAutos','Bellary',150,120,2,now(),'Admin19',now(),'Manager19');
SELECT * FROM show_room;
ALTER TABLE show_room MODIFY COLUMN id int;
ALTER TABLE show_room DROP INDEX location;
