CREATE DATABASE state;
USE state;
CREATE TABLE state_info(id int,s_name varchar(20),capital varchar(20),population int,language int);
ALTER TABLE state_info ADD COLUMN no_of_districts int, ADD COLUMN(area varchar(20),no_of_airports bigint,chief_minister int,it_hub boolean);
SELECT * FROM state_info;
ALTER TABLE state_info RENAME COLUMN s_name to state_name;
ALTER TABLE state_info RENAME COLUMN capital to s_capital;
ALTER TABLE state_info RENAME COLUMN population to s_population;
ALTER TABLE state_info RENAME COLUMN language to s_language;
ALTER TABLE state_info RENAME COLUMN it_hub to has_it_hub;
ALTER TABLE state_info MODIFY COLUMN s_population bigint;
ALTER TABLE state_info MODIFY COLUMN s_language varchar(20);
ALTER TABLE state_info MODIFY COLUMN area bigint;
ALTER TABLE state_info MODIFY COLUMN no_of_airports int;
ALTER TABLE state_info MODIFY COLUMN chief_minister varchar(30);
DESC state_info;
INSERT INTO state_info values(1,'Karnataka','Bengaluru',681000000,'Kannada',31,191791,8,'Siddaramaiah',true);
INSERT INTO state_info values(2,'Tamil Nadu','Chennai',815000000,'Tamil',38,130058,7,'M K Stalin',true);
INSERT INTO state_info values(3,'Maharashtra','Mumbai',123100000,'Marathi',36,307713,9,'Eknath Shinde',false);
INSERT INTO state_info values(4,'Uttar Pradesh','Lucknow',231500000,'Hindi',75,243286,6,'Yogi Adityanath',true);
INSERT INTO state_info values(5,'Gujarat','Gandinagar',72000000,'Gujarathi',33,196024,9,'Bhupendra Patel',false);
INSERT INTO state_info values(6,'West Bengal','Kolkata',996000000,'Bengali',23,88752,5,'Mamata Banerjee',true);
INSERT INTO state_info values(7,'Rajasthan','Jaipur',81000000,'Hindi',33,342239,7,'Ashok Gehlot',false);
INSERT INTO state_info values(8,'Kerala','Thiruvanthapuram',358000000,'Malayalam',14,38863,4,'Pinarayi Vijayan',false);
INSERT INTO state_info values(9,'Andra Pradesh','Amaravati',54000000,'Telugu',26,162968,6,'Y S Jagan Mohan Reddy',false);
INSERT INTO state_info values(10,'Madya Pradesh','Bhopal',85000000,'Hindi',52,308252,5,'Shivraj Singh',true);
INSERT INTO state_info values(11,'Telangana','Hyderabad',58000000,'Telugu',33,112077,3,'K Chandrashekar Rao',false);
INSERT INTO state_info values(12,'Punjab','Chandigarh',3000000,'Punjabi',22,50362,5,'Bhagawant Mann',true);
INSERT INTO state_info values(13,'Jharkand','Ranchi',39000000,'Hindi',24,79761,4,'Hemant Soren',false);
INSERT INTO state_info values(14,'Odisha','Bhubneshwar',47000000,'Odia',30,155707,6,'Naveen Patnaik',true);
INSERT INTO state_info values(15,'Goa','Panaji',15000000,'Konkani',2,3702,0,'Paramod Sawant',false);
INSERT INTO state_info values(16,'Bihar','Patna',124000000,'Hindi',38,94162,3,'Nitish Kumar',true);
INSERT INTO state_info values(17,'Assam','Dispur',35000000,'Assamese',34,78438,5,'Himanta Biswa sarma',true);
INSERT INTO state_info values(18,'Chattisgarh','Raipur',3000000,'Hindi',32,135192,4,'Bhupesh Baghel',false);
INSERT INTO state_info values(19,'Haryana','Chandigarh',29000000,'Hindi',22,44212,3,'Manohar Lal',true);
INSERT INTO state_info values(20,'Himachal Pradesh','Shimla',73000000,'Hindi',12,55672,5,'Sukhvinder Singh',true);
SELECT * FROM state_info;
UPDATE state_info SET s_language='Hindi' where id=3;
UPDATE state_info SET no_of_districts=29 where state_name='Karnataka';
UPDATE state_info SET has_it_hub=true where id=8;
UPDATE state_info SET no_of_airports=7 where state_name='Gujarat';
UPDATE state_info SET chief_minister='Y S Jagan' where id=9;
UPDATE state_info SET s_language='Punjabi' where s_capital='Chandigarh';
UPDATE state_info SET has_it_hub=false where id=17;
UPDATE state_info SET no_of_airports=1 where state_name='Goa';
UPDATE state_info SET chief_minister='Himanta Biswa' where id=17;
UPDATE state_info SET state_name='Goa' where id=15;
DELETE FROM state_info where id=15;
DELETE FROM state_info where state_name='Haryana';
DELETE FROM state_info where id=14;
SELECT * FROM state_info where id=4 AND id=7;
SELECT * FROM state_info where id=4 OR id=7;
SELECT * FROM state_info where id in(1,2,4,7);
SELECT * FROM state_info where id not in(1,2,4,7);
UPDATE state_info SET no_of_airports=5;
rollback;